### ISSUE TITLE
Even Split Recipients

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#11]
My understanding is that this should be for when the split is even among the whole group. I think this is where we want a collection of checkboxes and you can select between one and all of the recipients.

**Comment by melinath** [comment]
So basically, it's an even split among _these members_ as opposed to making them do a manual split. Okay. Makes sense to me.

**Comment by melinath** [comment]
This was resolved with c13bcbb1248b3122e296ea43d03491d83e96cda5.
