### ISSUE TITLE
Member detail balance

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#12]
What is balance x or x? Is this like rounded vs not? Mine all read x or x, not x or y.

**Comment by nmorduch** [comment]
I'm going to look in the code first and see if I can figure it out because that would have been a good thing to do before even opening this.

**Comment by nmorduch** [comment]
Ok still confused. Why would balance and member.balance be different from each other?

**Comment by melinath** [comment]
They wouldn't be. I'm just demonstrating that whoever is working on the template has multiple options for accessing that information, since I don't want you to have to look at the python code. :-)

**Comment by nmorduch** [comment]
Oh. You're great!

**Comment by nmorduch** [comment]
Though like it is probably a good idea to be looking at the Python code? I think I am getting the point where reading it is helpful even though I can't write it.
