### ISSUE TITLE
Add source/sink support.

### ISSUE THREAD

**Issue by melinath** [littleweaver/django-argus#15]
It might be useful to support sources and sinks.

Sources would be income that needs to be split among members, but comes from an external source. Sinks would be placeholders for third parties who are being paid.

For example, income from a contract could be modeled as a "source" which magically owes everyone money. Rent payments could be modeled as a "sink" which has _totally paid_ that one expense, and which everyone owes money to.

I think this overlaps with issue #7 - we could merge members, sources, and sinks into a single model.

**Comment by melinath** [comment]
Working on this.

**Comment by nmorduch** [comment]
I'm still not sure this makes sense, but I'll have to take a look at it this afternoon to understand better.

**Comment by nmorduch** [comment]
I totally hadn't realized that recipients were for the who-you-paid. I was thinking this would just be a text field that would autofill previous entries (like on a spreadsheet haha). I think that having to add recipients separately from adding expenses complicates the process, and I think that having a list to choose from would very quickly get unwieldy. The advantage I see to the sink/source system is that you would be able to get information about things like how much you'd spent at IGA (not worth the unwieldy list) or that you could record things like rent even though they didn't require any splitting, in which case I think there could just be a type of input for one-person's-expense-just-for-the-record.

**Comment by melinath** [comment]
@nmorduch I imagine that recipient, category and member fields will all be text fields that autofill previous entries. But that's all frontend sugar over the current system. Does this mean I should abandon the source/sink work? I would be fine with that, because it's kind of weird and I can't quite figure out how to make it work right.

**Comment by melinath** [comment]
I have a thing I'm sort of satisfied with and kinda like. See commit 775ef683336c9341582d812f4787f84bb4b1700b. Warning: requires resetting the db. Sorry.

It's an implementation of "sinks" at the same level as members. I think we could tweak this to also support sources if we ever wanted to. Otherwise, we can just leave it as is and get basically the same functionality we had before (but a little nicer in a few places.)

**Comment by nmorduch** [comment]
Can it work so that you input text and if it doesn't match any parties then it automatically creates a new one?

**Comment by melinath** [comment]
I _could_, but we probably want to do something a little smarter than that - otherwise people will accidentally mistype the name and create extraneous parties.

I'd recommend something like [chosen](http://harvesthq.github.io/chosen/).

**Comment by melinath** [comment]
I'm closing this because I think it's resolved enough for now... UI concerns should be a separate ticket.

**Comment by nmorduch** [comment]
ooh chosen looks really nice. I think this is still a question, though. I don't want people to start the input process then go oh shit I have to go make a new recipient. Can there be recipient creation without leaving the transaction form? I think that chosen would actually make it so that there would be little danger of the typo problem.
