### ISSUE TITLE
Navbar Questions (Template best practices)

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#17]
I would like to have a navbar that when not on a certain group just says like
- Argus
- About

and that when on a certain group says
- Argus
- Group Name
- Settings

But I am not sure the best-practices way to do that.

**Comment by melinath** [comment]
You would either do a template that checks whether you're "in a group", or you would have one navbar template used by group templates and one used by non-group templates. Either way is fine.

**Comment by nmorduch** [comment]
Do all views within the group have access to the group name?

**Comment by melinath** [comment]
Most of them do. Would you like me to add it to the rest of them?

**Comment by nmorduch** [comment]
Yes please! And the link to the group settings page, if that doesn't come free from that.

**Comment by melinath** [comment]
#25 is resolved... you should be able to do this now.

**Comment by nmorduch** [comment]
I think this is done already? Everything seems to be getting it fine.
