### ISSUE TITLE
Amount field doesn't accept decimals.

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-argus#28]
Some browsers, e.g., Chrome, enforce HTML5 input types. Amount is a "number" field, so entering a decimal returns this:
![screenshot 2014-03-14 18 15 23](https://f.cloud.github.com/assets/296631/2426461/29a3e2bc-abc6-11e3-85c8-74749e1e8adc.png)

**Comment by melinath** [comment]
Hah. That's funny.

**Comment by melinath** [comment]
It shouldn't be - that's an error in floppyforms, probably. Or Django.

**Comment by harrislapiroff** [comment]
Or potentially Chrome. Time to look at the HTML spec!

**Comment by harrislapiroff** [comment]
Seems impossible to say whose fault the bug is. Adding a `step="any"` attribute on the widget fixes the problem. W3C is non-specific as to what the step value should be by default. Chrome seems to assume 1, thereby limiting numerical options to the integers. Not what I'd do, but not strictly unreasonable. Neither Django nor Floppyforms put a step attribute in by default, which also doesn't seem unreasonable.

**Comment by harrislapiroff** [comment]
I might like to subclass NumberInput to MoneyInput or something and give it step=.01?

**Comment by harrislapiroff** [comment]
Nope, not necessary. This instantiation works fine:

``` python
forms.NumberInput(attrs={'step': 0.01})
```

**Comment by harrislapiroff** [comment]
resolved by 7fe46fe
