### ISSUE TITLE
Indentation of templates

### ISSUE THREAD

**Issue by harrislapiroff** [littleweaver/django-argus#3]
We should decide on an indentation scheme.

**Comment by melinath** [comment]
I generally like two spaces for templates, and four spaces for CSS, but I'm not super invested.

**Comment by harrislapiroff** [comment]
I actually prefer tabs for templates and CSS. I mean, I prefer tabs everywhere (screw you, PEP 8 :facepunch:) but in this case it actually has bandwidth implications. Though those concerns are obviated if we use some sort of compressor, I suppose.

**Comment by melinath** [comment]
Okay, then lets do tabs for HTML/CSS/SASS, yeah?
