### ISSUE TITLE
Login page should have less info

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#35]
Right now you get the sidebar and logout button on the login page. How do we test being logged in rather than testing the existence of a password? I guess I could just make the template for that one page different, but I think it would be better to have it a general test on group templates.

**Comment by melinath** [comment]
We would need something like group.is_authenticated() or something. We could probably add this, or add something to the context. But it would probably be easier to just modify the login page. That's the only page you'll see if you're not logged in and you should be.

**Comment by nmorduch** [comment]
It seems safer to me to have a check for being authenticated. Like in case there are ever other pages or something. I think I just have a preference for making things general when they can be.
