### ISSUE TITLE
Group Creation

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#5]
Create from a name rather than a random slug

**Comment by melinath** [comment]
Makes creation quicker to use a random slug, and they can change the name when they edit the group settings.

**Comment by nmorduch** [comment]
I agree with what you said in the meeting: create from names. Maybe like a field for a comma-separated-list would be really nice.

**Comment by melinath** [comment]
I was suggesting using a random slug, but also letting them optionally enter member names on the homepage.

**Comment by nmorduch** [comment]
Why should the names be optional? They will be unable to use the app at all until they enter names.
