### ISSUE TITLE
Members vs. Recipients

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#7]
Why are they different? I am not convinced they should be. Why do I have to add the same person in both places?

**Comment by melinath** [comment]
You don't. Members are not recipients. Recipients are third parties (Grocery stores, etc.). Members are people who can owe money or be owed money. Payments to members are presented to be as similar as payments to third parties as possible - but the mechanism is very different in the backend.

This is probably a design issue, not a database issue.
