### ISSUE TITLE
Manual Split Values

### ISSUE THREAD

**Issue by nmorduch** [littleweaver/django-argus#9]
Rather than requiring that it add up by percent or amount, can we just do for each person: the weight for that person divided by the sum of all of the weights
which will also work when they add up to percents or to the amount, but gives more flexibility.

**Comment by melinath** [comment]
This seems more confusing than flexible to me. It sounds like what splitwise called "shares" - could you give a use case that explains why this is useful?

**Comment by nmorduch** [comment]
1. It doesn't require doing arithmetic to input information.
2. It allows you do give people weights of 0, 1, and 2 (my preferred method of input), so that you can have a sloppy way of weighting people differently. Or not sloppy, if you're sharing a meal and one person is paying for two people.

**Comment by nmorduch** [comment]
And then always store as a percent.

**Comment by melinath** [comment]
If it's always stored as a percent, then this could just be a conversion done in the front-end, hypothetically.

**Comment by nmorduch** [comment]
On second thought, can we always store as shares? Then even split is just 1s and 0s, and M-->M is just one 1 among 0s.

**Comment by melinath** [comment]
I don't think that's a good idea, because percents allow more precision. And make more sense to some people. :-p That being said, I think that handling the share -> percent conversion in the backend is probably actually the way to go.

**Comment by melinath** [comment]
... although shares allow more precision if they're wonky things like splitting something 1:2:4. 1/7 is an awkward value to store.

**Comment by nmorduch** [comment]
Right, I was thinking you would store the numerators and denominator separately, for maximal precision. More precise than percents :p

**Comment by melinath** [comment]
This is basically what housetab does.

**Comment by nmorduch** [comment]
Maybe not everything they do is the worst :)
